### ISSUE TITLE
Project fails to compile

### ISSUE THREAD

**Issue by bienstock** [nimble-platform/catalog-service-backend#3]
Hi,

#### Just tried compiling the project using `mvn clean install` and got the following errors:

16:15:18.945 INFO  - worker execution interrupted on shutdown
16:15:18.945 INFO  - unregistering statistics module "Worker Statistics (Engine SOLR Core (dc) dc)"
16:15:18.945 INFO  - SOLR Core (dc) Worker Thread (dc,id=2) shutting down ...
16:15:18.945 INFO  - SOLR Core (dc) Worker Thread (dc,id=1) shutting down ...
16:15:18.945 INFO  - shutting down configuration service
16:15:18.945 INFO  - unregistering statistics module "HttpClientService"
16:15:18.945 INFO  - Apache Marmotta Sesame Repository Service shutting down ...
16:15:18.946 INFO  - shutting down KiWi persistence ...
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.333 sec - in at.newmedialab.lmf.search.SolrTemplatesTest

Results :

Failed tests: 
  SolrCoresTest.testCreateCore:94->testCoreExists:136 null

Tests in error: 
  SolrCoresTest.testCoreConfiguration:187 » CoreAlreadyExists the engine with na...

Tests run: 7, Failures: 1, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] NIMBLE Catalog Service ............................. SUCCESS [  0.173 s]
[INFO] Bundles for Catalog Services ....................... SUCCESS [  0.011 s]
[INFO] NIMBLE Catalog Search Dashboard .................... SUCCESS [  1.253 s]
[INFO] Identity Provider (Shiro) .......................... SUCCESS [  1.615 s]
[INFO] Alibaba Dependencies ............................... SUCCESS [  0.035 s]
[INFO] Object Composition ................................. SUCCESS [  0.329 s]
[INFO] AliBaba Blob Store ................................. SUCCESS [  0.042 s]
[INFO] Object Repository .................................. SUCCESS [  0.136 s]
[INFO] Connector to Alibaba Object Service ................ SUCCESS [  3.492 s]
[INFO] Marmotta Module: Visualisation, Editing of Catalogs  SUCCESS [  2.186 s]
[INFO] Marmotta Module: Workers ........................... SUCCESS [  9.521 s]
[INFO] Marmotta Util Collection ........................... SUCCESS [  0.025 s]
[INFO] SolrPlugins ........................................ SUCCESS [  0.404 s]
[INFO] Marmotta Search .................................... FAILURE [ 39.801 s]
[INFO] SKOSjs Webjar ...................................... SKIPPED
[INFO] Module: SKOS Editor ................................ SKIPPED
[INFO] Sesame Vocabulary Builder .......................... SKIPPED
[INFO] Sesame Vocabulary Builder :: Core .................. SKIPPED
[INFO] Sesame Vocabulary Builder :: CLI ................... SKIPPED
[INFO] Sesame Vocabulary Builder :: Maven Plugin .......... SKIPPED
[INFO] WebApp Container for the Nimble Catalog Service .... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 59.873 s
[INFO] Finished at: 2017-08-01T16:15:18+03:00
[INFO] Final Memory: 89M/266M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project marmotta-search: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/gadm/workspace/catalog-service-backend/libs/marmotta-search/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :marmotta-search

#### **The latest errors that appear are these:**

17:31:09.306 INFO  - Using Lucene MatchVersion: LUCENE_43
17:31:09.331 INFO  - Loaded SolrConfig: solrconfig.xml
17:31:09.331 INFO  - Reading Solr Schema from schema.xml
17:31:09.338 INFO  - [schema] Schema name=schema
17:31:09.504 INFO  - reloading core schema in embedded SOLR service
17:31:09.505 ERROR - Unable to reload core: schema
org.apache.solr.common.SolrException: No such core: schema
	at org.apache.solr.core.CoreContainer.reload(CoreContainer.java:1084)
	at at.newmedialab.lmf.search.services.cores.SolrCoreServiceImpl.reloadSolrCore(SolrCoreServiceImpl.java:897)
	at at.newmedialab.lmf.search.services.cores.SolrCoreServiceImpl.configurationChangedEvent(SolrCoreServiceImpl.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:93)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:266)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:253)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:232)
	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:169)
	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:165)
	at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:119)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:112)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:83)
	at org.apache.marmotta.platform.core.services.config.ConfigurationServiceImpl$EventTimerTask.run(ConfigurationServiceImpl.java:1592)
	at java.util.TimerThread.mainLoop(Timer.java:566)
	at java.util.TimerThread.run(Timer.java:516)
Exception in thread "Configuration Event Timer" org.apache.solr.common.SolrException: Unable to reload core: schema
	at org.apache.solr.core.CoreContainer.recordAndThrow(CoreContainer.java:1450)
	at org.apache.solr.core.CoreContainer.reload(CoreContainer.java:1132)
	at at.newmedialab.lmf.search.services.cores.SolrCoreServiceImpl.reloadSolrCore(SolrCoreServiceImpl.java:897)
	at at.newmedialab.lmf.search.services.cores.SolrCoreServiceImpl.configurationChangedEvent(SolrCoreServiceImpl.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:93)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:266)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:253)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:232)
	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:169)
	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:165)
	at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:119)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:112)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:83)
	at org.apache.marmotta.platform.core.services.config.ConfigurationServiceImpl$EventTimerTask.run(ConfigurationServiceImpl.java:1592)
	at java.util.TimerThread.mainLoop(Timer.java:566)
	at java.util.TimerThread.run(Timer.java:516)
Caused by: org.apache.solr.common.SolrException: No such core: schema
	at org.apache.solr.core.CoreContainer.reload(CoreContainer.java:1084)
	... 18 more
17:31:09.609 INFO  - default search field in schema is lmf.text_all
17:31:09.610 INFO  - query parser default operator is OR
17:31:09.612 INFO  - unique key field: id
17:31:09.637 INFO  - solr.NRTCachingDirectoryFactory
17:31:09.637 INFO  - [schema] Opening new SolrCore at /tmp/1501597864380-0/solr/schema/, dataDir=/tmp/1501597864380-0/solr/schema/data/
17:31:09.637 INFO  - JMX monitoring not detected for core: schema
17:31:09.637 INFO  - [schema] Added SolrEventListener for newSearcher: org.apache.solr.core.QuerySenderListener{queries=[]}
17:31:09.637 INFO  - [schema] Added SolrEventListener for firstSearcher: org.apache.solr.core.QuerySenderListener{queries=[{q=static firstSearcher warming in solrconfig.xml}]}
17:31:09.638 INFO  - solr.NRTCachingDirectoryFactory
17:31:09.638 INFO  - return new directory for /tmp/1501597864380-0/solr/schema/data

**Comment by oliver-jung** [comment]
The test cases of the "Marmotta Search" still require some adaption to the Catalog Service Backend.
Meanwhile the build should be executed using `mvn clean install -DskipTests=true`
